[package]
name = "structural_derive"
version = "0.0.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description="Derives for manipulating struct fields."

[dependencies]

[lib]
proc-macro = false