[package]
name = "structural"
version = "0.0.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description="For manipulating struct fields."

[dependencies]
structural_derive="0.0.0"